version: '3.8'

services:

  app:
    build:
      dockerfile: .docker/dev/app/Dockerfile
    volumes:
      - ./:/var/www/html
    hostname: client
    ports:
      - "3001:3001" # The Nuxt app port
      - "24678:24678" # The Vite port for WebSocket
    networks:
      - client
      - gateway

networks:
  client:
    name: client

  gateway:
    name: gateway
    external: true